@baseAddress = http://localhost:5178
@categoryId=c4d90000-b1ad-a497-8abd-08deb0e4986c

GET {{baseAddress}}/api/categories
Accept: application/json

###

GET {{baseAddress}}/api/categories/5
Accept: application/json


###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json

{
  "name": "New Course",
  "description": "This is a new course",
  "price": 99.99,
  "categoryId": "{{categoryId}}"
}